# Generated by Django 5.0.7 on 2024-11-18 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='province',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='start_date',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
