# Generated by Django 5.0.7 on 2024-11-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0002_remove_city_province_remove_banner_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(blank=True, default='No description provided.', null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='required_documents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_rules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_services',
            field=models.TextField(blank=True, null=True),
        ),
    ]
