# Generated by Django 5.0.7 on 2024-11-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0003_alter_tour_description_alter_tour_required_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
