# Generated by Django 5.0.7 on 2024-12-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0004_alter_tour_description_alter_tour_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verification_code',
            field=models.CharField(default='2345', max_length=4),
        ),
    ]
